# Generated by Django 6.1.1 on 2026-09-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceexception',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='servicetime',
            options={'ordering': ['weekday', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['table_number']},
        ),
    ]
