# Generated by Django 6.1.1 on 2026-09-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_serviceexception_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(unique=True),
        ),
    ]
