# Generated by Django 6.1.1 on 2026-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_table_table_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'time', '-guest_count']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.IntegerField(default=120),
        ),
    ]
