# Generated by Django 6.1.1 on 2026-09-13 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_reservation_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='res_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
