# Generated by Django 6.1.1 on 2026-09-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_options_reservation_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['svc_date', 'time', '-guest_count']},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='svc_date',
        ),
    ]
