# Generated by Django 6.1.1 on 2026-09-12 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Booked'), (1, 'Arrived')], default=0),
        ),
    ]
