# Generated by Django 6.1.1 on 2026-09-15 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField()),
                ('admin_comment', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('price', models.PositiveIntegerField(help_text='Price in pence')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.course')),
            ],
        ),
    ]
