# Generated by Django 6.1.1 on 2026-09-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='admin_comment',
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
